-- Create Businesses Table
create table businesses (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  category text not null,
  description text,
  phone text,
  whatsapp text,
  address text,
  image text,
  is_open boolean default false,
  is_featured boolean default false,
  delivery boolean default false,
  is_paid boolean default false,
  start_date date,
  expiration_date date,
  hours jsonb,
  tags jsonb,
  payment_methods jsonb,
  promotions text
);

-- Create Categories Table
create table categories (
  id bigint generated by default as identity primary key,
  name text unique not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS) - Optional for now or set to public
alter table businesses enable row level security;
alter table categories enable row level security;

-- Create Policies for Public Read Access
create policy "Public businesses are viewable by everyone."
  on businesses for select
  using ( true );

create policy "Public categories are viewable by everyone."
  on categories for select
  using ( true );

-- Create Policies for Admin Insert/Update/Delete (Ideally authenticated)
-- For simplicity in this step, we'll allow all operations if you have the key, 
-- BUT in production you should use Supabase Auth.
-- Here we just allow all for now to get it working with the Anon Key + RLS disabled or open policies.
create policy "Enable all access for all users"
    on businesses for all 
    using (true) 
    with check (true);

create policy "Enable all access for all users"
    on categories for all 
    using (true) 
    with check (true);
